click = '../lib/music/click.mp3'
menu = '../lib/music/rock.mp3'
dammit = '../lib/music/blink.mp3'
fortunate_son = '../lib/music/ccr.mp3'
immigrant_song = '../lib/music/led_zeppelin.mp3'
all_along_the_watchtower = '../lib/music/jimi.mp3'
dream_on = '../lib/music/aerosmith.mp3'